const mongoose = require('mongoose');

const resourceSchema = new mongoose.Schema({
      name:{
        type: String,
        required: true
      },
      url:{
        type: mongoose.SchemaTypes.Url,
        required: true
      },
      createdBy:{
        type: String, 
        required: false
      },
      description:{
        type: String, 
        required: false,
        default:"resource generated by magic tutorial tracks"
      },
      imageUrls:{
        type: Array, 
        required: false,
        default:["https://user-images.githubusercontent.com/3622055/42908563-4778bd04-8aaf-11e8-95c1-47e18c0643a4.png"]
      },
      dateSubmitted:{
        type: Date, 
        required: true, 
        default: Date.now
      }
    });

const Resource = mongoose.model("Resource", resourceSchema);

module.exports = Resource;