const mongoose = require('mongoose');
// const sectionSchema = require("./section")

const resourceSchema = new mongoose.Schema({
      name:{
        type: String,
        required: true
      },
      url:{
        type: mongoose.SchemaTypes.Url,
        required: true
      },
      createdBy:{
        type: String, 
        required: false
      },
      description:{
        type: String, 
        required: false,
        default:"resource generated by magic tutorial tracks"
      },
      imageUrls:{
        type: Array, 
        required: false,
        default:["https://user-images.githubusercontent.com/3622055/42908563-4778bd04-8aaf-11e8-95c1-47e18c0643a4.png"]
      },
      dateSubmitted:{
        type: Date, 
        required: true, 
        default: Date.now
      }
    });

const sectionSchema = new mongoose.Schema({
      section:{
        type: Number,
        required: true
      },
      name: {
        type: String, 
        required: true
      },
      createdBy:{
        type: String, 
        required: false
      },
      description:{
        type: String, 
        required: false,
        default:"tutorial generated by magic tutorial tracks"
      },
      imageUrls:{
        type: Array, 
        required: false,
        default:["https://user-images.githubusercontent.com/3622055/42908563-4778bd04-8aaf-11e8-95c1-47e18c0643a4.png"]
      },
      resources:{
        type:[resourceSchema],
        ref: 'Resource'
      },
      dateSubmitted:{
        type: Date, 
        required: true, 
        default: Date.now
      }
    });

const tutorialSchema = new mongoose.Schema({
      name: {
        type: String, 
        required: true
      },
      repoName:{
        type: String, 
        required: true
      },
      createdBy:{
        type: String, 
        required: true
      },
      description:{
        type: String, 
        required: false,
        default:"tutorial generated by magic tutorial tracks"
      },
      collaborators:{
        type: Array, 
        required: false
      },
      imageUrls:{
        type: Array, 
        required: false,
        default:["https://user-images.githubusercontent.com/3622055/42908563-4778bd04-8aaf-11e8-95c1-47e18c0643a4.png"]
      },
      tutorial:{
        type: [sectionSchema],
        ref:'Section'
      },
      dateSubmitted:{
        type: Date, 
        required: true, 
        default: Date.now
      }
    });

const Tutorial = mongoose.model("Tutorial", tutorialSchema);

module.exports = Tutorial;